# Generated by Django 5.0.7 on 2024-07-28 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('activation', 'Activation'), ('income', 'Income'), ('spend', 'Spend')], default='income', max_length=20)),
                ('amount', models.PositiveBigIntegerField(default=0, verbose_name='Amount')),
                ('balance', models.PositiveBigIntegerField(default=0, verbose_name='Balance')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Balance Operation Log',
                'verbose_name_plural': 'Balance Operation Logs',
            },
        ),
    ]
